name: DAST with ZAP

on:
  workflow_run:
    workflows: ["Deploy Docker latest image with a SSH push"]
    types: [completed]

jobs:
  dast:
    runs-on: ubuntu-latest
    name: Scan the deployed app
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: "Setup AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: "Terraform get EC2 public IP"
        run:  |
          cd terraform
          terraform init
          EC2_PUBLIC_IP=$(terraform output -raw deployed_public_ip)
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: "http://${{ env.EC2_PUBLIC_IP }}:8080"
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -x report.xml'
