name: Build docker image and push to repository
description: Idk

on:
  push:
    branches:
      - main

jobs:
  push_image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vbolzani/juice-shop-dso:${{ github.sha }}

  deploy:
    name: Deploy with SSH
    runs-on: ubuntu-latest
    depends_on: push_image
    steps:
      - name: Setup SSH key
        run: |
          echo "$EC2_PRIVATE_KEY" > private.key
          sudo chmod 600 private.key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_SECRET_KEY }}

      - name: "Copying deploy script"
        run: |
          scp -o StrictHostKeyChecking=no -i private.key ./deploy.sh ubuntu@${EC2_PUBLIC_IP}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no -i private.key ubuntu@${EC2_PUBLIC_IP} chmod +x /home/ubuntu/deploy.sh
      
      - name: "Executing deploying script"
        run: |
          ssh -o StrictHostKeyChecking=no -i private.key ubuntu@${EC2_PUBLIC_IP} /home/ubuntu/deploy.sh

