name: SCA/SAST Scans

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Run Snyk to check terraform security
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=iac.sarif
      
      - name: Run Snyk to check Node security
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=node.sarif

      - name: Upload Snyk IaC results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: iac.sarif
          category: terraform-sast

      - name: Upload Snyk IaC results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: node.sarif
          category: node-js-sast