name: Build docker image and push to repository

on:
  pull_request:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Run Snyk to check terraform security
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=iac.sarif
      
      - name: Run Snyk to check Node security
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=node.sarif

      - name: Upload Snyk results
        uses: github/codeql-action/upload-sarif@v3